spring.application.name=fasks

# Database configuration
spring.datasource.url = jdbc:h2:file:./backend/data/fasksdb
spring.datasource.driverClassName = org.h2.Driver
spring.datasource.username = sa
spring.datasource.password =
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

# Removing soon
# spring.jpa.hibernate.ddl-auto=create-drop

# application data
app.jwt-secret= @ferd-pele-fern-bern-2019-2026-fasks-appication.
app.jwt-expiration=86400000